name: csust-electricity-monitor

services:
  electricity-monitor:
    image: youzijiang/csust-electricity-monitor:latest
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
